Repository adobe/aio-cli-plugin-api-mesh, pull requests merged in 2025-05, with the labels that each got.

#246 Cext 4511
  package.json
  src/commands/api-mesh/__tests__/set-log-forwarding.test.js
  src/commands/api-mesh/config/set/log-forwarding.js
  src/utils.js
  yarn.lock
Labels: enhancement

#252 fix(bigint-serialization): - Fixed OpenAPI source BigInt scalar serialization to JSON
  package.json
  src/worker.js
  yarn.lock
Labels: bug, Version: Patch

#262 Chore/local dev remote hook
  package.json
  src/__tests__/meshArtifact.test.js
  src/meshArtifact.js
Labels: enhancement, Version: Minor
